site_name: Python Template Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Python Template: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md